//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public Nullable<System.DateTime> setup_date { get; set; }
        public Nullable<int> setup_by { get; set; }
        public string status_code { get; set; }
        public string ship_to_bill_ind { get; set; }
        public string website_url { get; set; }
        public string account_number { get; set; }
        public string override_validation_ind { get; set; }
        public Nullable<long> parent_id { get; set; }
        public string parent_ind { get; set; }
    }
}
