//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string order_number { get; set; }
        public string order_type { get; set; }
        public string purchase_order { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.DateTime> order_due_date { get; set; }
        public string order_status { get; set; }
        public Nullable<int> taken_user_id { get; set; }
        public Nullable<int> assigned_user_id { get; set; }
        public Nullable<System.DateTime> est_begin_date { get; set; }
        public Nullable<System.DateTime> act_begin_date { get; set; }
        public Nullable<System.DateTime> est_complete_date { get; set; }
        public Nullable<System.DateTime> act_complete_date { get; set; }
        public Nullable<System.DateTime> shipped_date { get; set; }
        public string subtotal { get; set; }
        public string tax_rate { get; set; }
        public string tax_amount { get; set; }
        public string shipping { get; set; }
        public string total { get; set; }
        public string payments { get; set; }
        public string balance_due { get; set; }
        public string IMAGE_FILE { get; set; }
        public string BILL_ADDRESS_1 { get; set; }
        public string BILL_ADDRESS_2 { get; set; }
        public string BILL_CITY { get; set; }
        public string BILL_STATE { get; set; }
        public string BILL_ZIP { get; set; }
        public string SHIP_ADDRESS_1 { get; set; }
        public string SHIP_ADDRESS_2 { get; set; }
        public string SHIP_CITY { get; set; }
        public string SHIP_STATE { get; set; }
        public string SHIP_ZIP { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public string PERCENT_COMPLETE { get; set; }
        public string ship_carrier { get; set; }
        public string ship_tracking { get; set; }
        public string previous_order { get; set; }
        public string reorder_ind { get; set; }
        public string ship_attn { get; set; }
        public string contact { get; set; }
        public string contact_email { get; set; }
        public string contact_phone1 { get; set; }
        public string contact_phone1_ext { get; set; }
        public string contact_phone1_type { get; set; }
        public string contact_phone2 { get; set; }
        public string contact_phone2_ext { get; set; }
        public string contact_phone2_type { get; set; }
    }
}
