//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_status_history
    {
        public int order_status_history_id { get; set; }
        public string order_id { get; set; }
        public string order_status { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public Nullable<int> set_by_user_id { get; set; }
    }
}
