//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class pricelist
    {
        public int pricelist_id { get; set; }
        public Nullable<int> order_by { get; set; }
        public string pricelist_type { get; set; }
        public string pricelist_description { get; set; }
        public string pricelist_code { get; set; }
        public string pricelist_price { get; set; }
        public string taxable_ind { get; set; }
        public string default_ind { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
