//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string login_id { get; set; }
        public Nullable<int> manager_id { get; set; }
        public string password { get; set; }
        public Nullable<int> login_attempt_count { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string status_code { get; set; }
        public string language_code { get; set; }
        public Nullable<int> wu_id { get; set; }
        public string lookup_item_code { get; set; }
        public string current_group { get; set; }
        public string order_search_for { get; set; }
        public string order_search_code { get; set; }
        public string current_table { get; set; }
        public string customer_search_for { get; set; }
        public string customer_search_code { get; set; }
        public string pass_change_1 { get; set; }
        public string pass_change_2 { get; set; }
        public string edit_email { get; set; }
        public string edit_subject { get; set; }
        public string edit_message { get; set; }
        public string report_sel { get; set; }
        public string corr_type { get; set; }
        public string corr_disp { get; set; }
        public string task_list_type { get; set; }
        public string pricelist_type { get; set; }
        public string active_order_ind { get; set; }
        public Nullable<System.DateTime> order_search_date { get; set; }
        public string task_type_code { get; set; }
        public string order_parent_search_for { get; set; }
        public string order_type_search_for { get; set; }
        public Nullable<int> assigned_to_search_for { get; set; }
    }
}
